UPDATE posts SET image_urls='/img/四姑娘山.jpg' WHERE title='四姑娘山大峰攀登全记录' AND id >= 25;
UPDATE posts SET image_urls='/img/虎跳峡.jpg' WHERE title='虎跳峡高路徒步 - 世界十大经典徒步路线体验' AND id >= 25;
UPDATE posts SET image_urls='/img/徒步装备.avif' WHERE title='秋季徒步装备指南 - 从入门到专业的完整清单' AND id >= 25;
UPDATE posts SET image_urls='/img/贡嘎转山.png' WHERE title='贡嘎转山 - 蜀山之王的朝圣之旅' AND id >= 25;
UPDATE posts SET image_urls='/img/稻城亚丁.jpg' WHERE title='稻城亚丁徒步 - 最后的香格里拉' AND id >= 25;
UPDATE posts SET image_urls='/img/雨崩村.webp' WHERE title='雨崩村徒步 - 梅里雪山脚下的秘境' AND id >= 25;
UPDATE posts SET image_urls='/img/喀纳斯.jpg' WHERE title='喀纳斯徒步 - 中国最美的人间净土' AND id >= 25;
UPDATE posts SET image_urls='/img/墨脱.jpg' WHERE title='墨脱徒步 - 中国最神秘的徒步路线' AND id >= 25;
UPDATE posts SET image_urls='/img/黄山.jpg' WHERE title='黄山徒步 - 中国山水之美典范' AND id >= 25;
UPDATE posts SET image_urls='/img/露营装备.jpg' WHERE title='徒步露营装备指南 - 野外安营扎寨的必备装备' AND id >= 25;
UPDATE posts SET image_urls='/img/徒步鞋履.jpg' WHERE title='徒步鞋履指南 - 选择合适的徒步鞋' AND id >= 25;
UPDATE posts SET image_urls='/img/服装系统.jpg' WHERE title='徒步服装系统指南 - 分层着装的艺术' AND id >= 25;
UPDATE posts SET image_urls='/img/导航与安全.jpg' WHERE title='徒步导航与安全装备指南 - 确保徒步安全的关键' AND id >= 25;
UPDATE posts SET image_urls='/img/背包装备.jpg' WHERE title='徒步背包装备指南 - 选择合适的背包' AND id >= 25;
UPDATE posts SET image_urls='/img/其他配件.jpg' WHERE title='徒步其他配件指南 - 提升徒步体验的小物件' AND id >= 25;